= Concurent Cooking
Gaëtan La Marca <lamarca.gaetan@gmail.com>
v1.2, 2015-12-12
:toc:

This application uses https://www.python.org/[Python 3.4], https://www.djangoproject.com/[Django 1.9], http://www.postgresql.org/[PostgreSQL 9.4] and http://getbootstrap.com/[Bootstrap].

This application is made to manage Cooking and It stuffs. +
The Cooking side contains recipes, ingredients,techniques management and consulting.
The it side contain form the moment only a bunch of RSS feed

This is an ALPHA version, the remaining jobs are listed in the issues of this https://github.com/glamarca/ConcurrentCooking/issues[github repository].

[NOTE]
====
All the following bash command are made on https://getfedora.org/[Fedora]. +
`dnf` is used as package management (>=Fedora 22) +
On other https://access.redhat.com/products/red-hat-enterprise-linux/[RHEL] distribution (https://www.centos.org/[CentOS],< Fedora 22,...) use `yum` +
On https://www.debian.org/[Debian] distribution (https://www.debian.org/[Debian Linux], http://www.ubuntu.com/[Ubuntu], http://www.linuxmint.com/[LinuxMint],...) use `apt-get`
====

== Creation and configuration of the Python VirtualEnv

[NOTE]
====
We assume that python3 and pip3 is installed.
====

To provide isolation between incompatible version of python, we must create a python virtual environment , and run our code inside this environment. We also have to configure this environment.

=== Install virtualenv

[source,bash]
----
$ sudo pip3 install virtualenv
----

=== Create new virtual environment

[source,bash]
----
$ virtualenv -p /path/to/python3_bin ENV
# In most of the cases , python3 lib is located to /usr/bin/python3
----

`ENV` is the folder where you want to create the virtual environment

=== Activate the virtual environment

If you activate a virtual environment , it change the `$PATH` variable , the shell will first look into `ENV/bin` folder. +
If you use `python3` command in the shell , it will use yhe python3 binary located in `ENV/bin` folder.

[source,bash]
----
$ cd ENV
$ source ./bin/activate

# Ex:
(VirtTest)[user@localhost VirtTest] $ python --version
Python 3.4.2
(VirtTest)[user@localhost VirtTest] $ pip --version
pip 7.1.2 from site-packages (python 3.4)
----

[NOTE]
====
From here whe assume that the virtualenv will be activated and used.
So, don't forget to activate the `ENV` before executing commands
====

=== Install Django in the virtual environment

[source,bash]
----
(VirtTest)[user@localhost VirtTest] $ pip install django
Collecting django
  Using cached Django-1.9-py2.py3-none-any.whl
Installing collected packages: django
Successfully installed django-1.9
----

== Clone the project

Create a folder where to store the project.
Clone the project inside the directory.

[source,bash]
----
(VirtTest)[user@localhost VirtTest] $ mkdir PROJECT_PATH
(VirtTest)[user@localhost VirtTest] $ cd PROJECT_PATH
(VirtTest)[user@localhost VirtTest] $ git clone https://github.com/glamarca/ConcurrentCooking.git ./
Clonage dans '.'...
remote: Counting objects: 180, done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 180 (delta 37), reused 177 (delta 34), pack-reused 0
Réception d'objets: 100% (180/180), 371.51 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (37/37), fait.
Vérification de la connectivité... fait.
----

=== Initialisation of the project

== Database initialisation and Presentation/Test data loading

We are going to use the `makemigration` and `migrate` command from `manage.py` to initialise the database with the default models (auth,admin,...) and the models written int the applications. +
Those scripts will discover every models of the applications that are listed in `INSTALLED_APPS` from the `settings.py`

=== Initialise DB models

[NOTE]
====
For development and testing purpose , https://www.sqlite.org/[SQLite3] will be used as and embedded database. +
If you want to clear the DB , just delete the `concurent_cooking_db` file in the project folder. It will be created by using `migrate` command. +
For Qa or Prod purpose , see the xref:postgres_install[PostGreSQL section].
====

[source,bash]
----
(VirtTest)[user@localhost VirtTest] $ cd $PROJECT_PATH

# Create the migration files
(VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py makemigrations cooking
No changes detected in app 'cooking'
# Make the migration
(VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py migrate
Operations to perform:
  Apply all migrations: sessions, auth, contenttypes, cooking, admin
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying cooking.0001_initial... OK
  Applying cooking.0002_auto_20151211_0339... OK
  Applying cooking.0003_auto_20151211_2241... OK
  Applying sessions.0001_initial... OK
----

=== Load Test Data

The test data are located in the *PROJECT_PATCH/cooking/fixtures* folder. +
Django look after script in the fixtures folders in each module. +
These data will also be used in initialisation of the test environment. +
The data files can be writen in json, xml and yaml.

[source,bash]
----
(VirtTest)[user@localhost VirtTest] $ cd $PROJECT_PATH

# Flush all data
# !!! If you flush the date , you have to recreate users and innitialise DB !!!
$ (VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py flush
You have requested a flush of the database.
This will IRREVERSIBLY DESTROY all data currently in the 'concurent_cooking_db' database,
and return each table to an empty state.
Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: yes


# Load data
$ (VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py loaddata 001_ingredient_test_data.json
Installed 46 object(s) from 1 fixture(s)
$ (VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py loaddata 002_recipe_test_data.json
Installed 1 object(s) from 1 fixture(s)
$ (VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py loaddata 003_ingredient_recipe_test_data.json
Installed 6 object(s) from 1 fixture(s)

----

== Users and permissions initialisation

=== Create Django admin user

To access the administration console of Django and manage users and group , you have to create an `admin` user.

[source,bash]
----
$ (VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py createsuperuser
Username (leave blank to use 'user'): admin
Email address: admin@email.org
Password:
Password (again):
Superuser created successfully.
----

=== Run the server and access to the administration console

[NOTE]
====
The `runserver`command purpose is to provide a quick django server for development.+
To use your code on a production server , you have to use apache https://modwsgi.readthedocs.org/en/develop/[mod_wsgi] (see xref:mod_wsgi[mod_wsgi section]).
Other option are also available. (see https://docs.djangoproject.com/fr/1.9/howto/deployment/ [django doc])
====

[source,bash]
----
$ (VirtTest)[user@localhost PROJECT_FOLDER] $ python ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2015 - 02:33:07
Django version 1.9, using settings 'concurent_cooking.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
----

Now, you can access the administration console at http://127.0.0.1:8000/admin/login/?next=/admin/. +
You can log in , using the admin user and password.

=== Add users, groups and permissions

We are going to create 2 users (one for cooking , one for it), which belong to 2 groups containing different permissions.

* Access to the http://127.0.0.1:8000/admin/login/?next=/admin/[administration console]
* Click on `Add User`
* Fill in the informations and click on `save`
* Do the same for the second user.
* Return to http://127.0.0.1:8000/admin/login/?next=/admin/[administration home page]
* Click on 'Add Group'
* Create the "it" group and give it all the "it" permission (Can change recipe , Can delete ingredient, ...)
* Click on `save`
* Do the same for the "cooking" group and give it all the "cooking" permissions
* Return to http://127.0.0.1:8000/admin/login/?next=/admin/[administration home page]
* Click on 'Modify User'
* Click on the "it" user
* Add the user in "it" group
* Click on `save`
* Do the same for the "cooking" user

.We have now 3 users :
* An "admin" user who can access the administration console and all the readable content.
* An "it" user who cannot access the administration stuffs but who can update create and delete all the "it" objects.
* A "cooking" user who cannot access the administration stuffs but who can update create and delete all the "cooking" objects.


[[postgres_install]]
== Install and configure PostGreSQL database

First we need to install postgreSQL on the system.

==== Installation

[source,bash]
----
# Install with dnf
# Dev package has to be installed to work with the python driver
(VirtTest)[user@localhost PROJECT_FOLDER] $ sudo dnf install postgesql-server.x86_64 python3-devel.x86_64 postgresql-devel.x86_64 postgresql-plpython3.x86_64 glibc-devel.x86_64

# Initialisation
(VirtTest)[user@localhost PROJECT_FOLDER] $ sudo postgresql-setup initdb

# Start the service
(VirtTest)[user@localhost PROJECT_FOLDER] $ sudo systemctl start postgresql.service

# Optional : if you want to run the service on startup
(VirtTest)[user@localhost PROJECT_FOLDER] $ sudo systemctl enable postgresql.service
----

==== Postgres SuperUser
By default, a *postgres* user is created, it is the SU of postgreSQL. +
We have to set a password to this user.

[NOTE]
====
By default, postgreSQL use an OS user as DB user. +
The *postgres* user was also created on the System, and you have to switch to this user to connect to postgreSQL as *postgres* user.

Later we will configure the postgreSQL service to allow connection with user and password without a corresponding linux user.
====

[source,bash]
----
# Switch to root
(VirtTest)[user@localhost PROJECT_FOLDER] $ sudo su
Enter password :

#Switch to posgres user
[root@localhost PROJECT_FOLDER] $ su postgres
[postgres@localhost PROJECT_FOLDER] $

#Start postgreSQL prompt
[postgres@localhost PROJECT_FOLDER] $ psql

#You should see something like this
could not change directory to "/root"
Welcome to psql 8.3.1, the PostgreSQL interactive terminal.
Type:  \copyright for distribution terms
       \h for help with SQL commands
       \? for help with psql commands
       \g or terminate with semicolon to execute query
       \q to quit
postgres=#

# Set password
ALTER USER postgres WITH PASSWORD 'password';
----

==== Create Django user for postgreSQL

[source,bash]
----
# Switch to root
(VirtTest)[user@localhost PROJECT_FOLDER] $ sudo su
Enter password :

#Switch to posgres user
[root@localhost PROJECT_FOLDER] $ su postgres

bash-3.x$

#Start postgreSQL prompt
$ psql

> CREATE USER django WITH PASSWORD 'password';
> CREATE DATABASE my_db;
> GRANT ALL PRIVILEGES ON DATABASE my_db to django;
> \q
----

==== Configure postgres to accept user/password connection without linux user

[source,bash]
----
# edit the file /var/lib/pgsql/data/pg_hba.conf (as root)
[root@localhost PROJECT_FOLDER] $ vim /var/lib/pgsql/data/pg_hba.conf

#¸Change those lines to set the authentification method to md5

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 ident
----

[NOTE]
====
This is a example configuration. +
To use this in a real environment , you have to grant acces using user/password only from accepted IP/network.
====


==== Configure Django to use PostgreSQL
https://docs.djangoproject.com/fr/1.9/ref/databases/#postgresql-notes[Django PostgreSQL documentation]

===== Install psycopg2
http://initd.org/psycopg/[psycopg2] is the python driver to use postgeSQL db.

[source,bash]
----
(VirtTest)[user@localhost VirtTest] $ pip3 install psycopg2
Collecting psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.6.1
----

===== Configure the settings.py

[source,python]
----
import psycopg2.extensions

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME' : 'my_db',
        'USER' : 'django',
        'PASSWORD' : 'password',
        'HOST' : 'localhost',
        'PORT' : '',
        'OPTIONS': {
            'isolation_level': psycopg2.extensions.ISOLATION_LEVEL_SERIALIZABLE,
            },
    }
}
----

[[tests]]
== Managing Tests

=== Unit Tests

[NOTE]
====
Normaly, Django can find any tests in applications folders if the test class extends `django.test.TestCase` , or any methods beginning by `test`. +
But due to what it seems to be a bug in the relative path finding in `runloader.py` from the os python bin, django doesn't find test classes in subfolders. +
It works if you pass the class path to the command line. To make it easy , i've added a `launch_test.py` script to launch the tests. See below for configuration of this file.
====

Django will search test class in all the subfolder of the application , if no test file is found on the root folder.
(Not working , see Not)

We will place test classes in `tests` folder in each application.
To run the tests we will use `manage.py test`.

[source,bash]
----
(VirtTest)[user@localhost PROJECT_FOLDER] $ python manage.py test <app>.[<folder>].TestClassName
# Ex : cooking.tests.IngredientRecipeTests
----

Any classes inplementing `django.test.TestCase` and any methods starting with `test` will be recognized as test methods or classes.

==== launch_test.py

To avoid the problem with the discover of test classes , we will use the `launch_test.py` script to launch the test. +
You have to add new test classes in the `TESTS_CLASSES` variable in `launch_test.py` file.

[source,python]
----
TESTS_CLASSES = [
    'cooking.tests.IngredientTests',
    'cooking.tests.RecipeTests',
    'cooking.tests.IngredientRecipeTests',
]
----

To launch the test , execute the following command

[source,bash]
----
(VirtTest)[user@localhost PROJECT_FOLDER] $ launch_tests.py
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: messages, staticfiles
  Apply all migrations: contenttypes, sessions, cooking, auth, admin
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying cooking.0001_initial... OK
  Applying cooking.0002_auto_20151211_0339... OK
  Applying cooking.0003_auto_20151211_2241... OK
  Applying sessions.0001_initial... OK
test_create_ingredient (cooking.tests.IngredientTests.IngredientMethodTests) ... ok
test_delete_ingredient (cooking.tests.IngredientTests.IngredientMethodTests) ... ok
test_update_ingredient (cooking.tests.IngredientTests.IngredientMethodTests) ... ok
test_create_recipe (cooking.tests.RecipeTests.RecipeMethodsTests) ... ok
test_delete_recipe (cooking.tests.RecipeTests.RecipeMethodsTests) ... ok
test_update_recipe (cooking.tests.RecipeTests.RecipeMethodsTests) ... ok
test_create_ingredient_recipe (cooking.tests.IngredientRecipeTests.IngredientRecipeMethodsTests) ... ok
test_delete_ingredient_recipe (cooking.tests.IngredientRecipeTests.IngredientRecipeMethodsTests) ... ok
test_update_ingredient_recipe (cooking.tests.IngredientRecipeTests.IngredientRecipeMethodsTests) ... ok

----------------------------------------------------------------------
Ran 9 tests in 0.016s

OK
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
----

*As you can see, a test database is created , initialised and destroyed at the end of the test.*

=== Selenium Tests

http://docs.seleniumhq.org/[Selenium] is a web browser automating tools : you can reproduce any action of a user on a web browser. +
It can be used to test webapplication reaction on user action.

The easiest way to create test case with selenium is to use the http://docs.seleniumhq.org/projects/ide/[Fiferfox Plugin] to record the user actions, and export them into python code.
Django provide a `LiveServerTestCase` class to interact with selenium.

==== Install selenium

[source,bash]
----
(VirtTest)[user@localhost PROJECT_FOLDER] $ pip install selenium
Collecting selenium
  Downloading selenium-2.48.0.tar.gz (805kB)
    100% |████████████████████████████████| 806kB 781kB/s
Building wheels for collected packages: selenium
  Running setup.py bdist_wheel for selenium
  Stored in directory: /home/user/.cache/pip/wheels/e1/34/09/4fa6eb65a3e9fded7ce3ee306ef8d398b09f35db4438567b23
Successfully built selenium
Installing collected packages: selenium
Successfully installed selenium-2.48.0
----

[[mod_wsgi]]
== Deployement using mod_wsgi

Doc : https://docs.djangoproject.com/fr/1.9/howto/deployment/wsgi/modwsgi/[Django avec Apache et mod_wsgi]
