# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20151211_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now)),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('VG', 'Vegetable'), ('MT', 'Meat'), ('FT', 'Fruit'), ('CL', 'Cereal'), ('SP', 'Spice'), ('MK', 'Milky'), ('SG', 'Sugar'), ('OL', 'Oil'), ('OT', 'Other'), ('FA', 'Fat'), ('EG', 'Eggs'), ('DA', 'Dough'), ('DF', 'Dried fruit')], default='OT', max_length=5),
        ),
    ]
