# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1450020596);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1450020716);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1450031036);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1450020476);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1450020356);
user_pref("asciidoctorlivepreview.enabled", true);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "BE");
user_pref("browser.search.region", "BE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150708165822");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1450036242");
user_pref("browser.slowStartup.averageTime", 2062);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150708165822");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"toggle-button--asciidoctor-firefox-addonasciidoctororg-enable-disable-btn\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"toggle-button--asciidoctor-firefox-addonasciidoctororg-enable-disable-btn\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1450020179421");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1450020180440");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1450106580440");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1448368328184");
user_pref("datareporting.policy.firstRunTime", "1448368194643");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 1526);
user_pref("datareporting.sessions.current.main", 247);
user_pref("datareporting.sessions.current.sessionRestored", 1994);
user_pref("datareporting.sessions.current.startTime", "1450036240066");
user_pref("datareporting.sessions.current.totalTime", 28);
user_pref("datareporting.sessions.currentIndex", 11);
user_pref("datareporting.sessions.previous.10", "{\"s\":1450035096680,\"a\":4,\"t\":28,\"c\":false,\"m\":517,\"fp\":1893,\"sr\":2341}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1450020104788,\"a\":77,\"t\":11120,\"c\":true,\"m\":9776,\"fp\":11902,\"sr\":12622}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1450031603367,\"a\":18,\"t\":121,\"c\":true,\"m\":111,\"fp\":1482,\"sr\":1982}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1450031734014,\"a\":7,\"t\":31,\"c\":false,\"m\":90,\"fp\":1132,\"sr\":1716}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1450033633608,\"a\":2,\"t\":13,\"c\":false,\"m\":297,\"fp\":1988,\"sr\":2219}");
user_pref("datareporting.sessions.prunedIndex", 5);
user_pref("dom.mozApps.used", true);
user_pref("extensions.asciidoctor-firefox-addon@asciidoctor.org.sdk.baseURI", "resource://asciidoctor-firefox-addon-at-asciidoctor-dot-org/");
user_pref("extensions.asciidoctor-firefox-addon@asciidoctor.org.sdk.domain", "asciidoctor-firefox-addon-at-asciidoctor-dot-org");
user_pref("extensions.asciidoctor-firefox-addon@asciidoctor.org.sdk.load.reason", "startup");
user_pref("extensions.asciidoctor-firefox-addon@asciidoctor.org.sdk.rootURI", "jar:file:///home/sarace/.mozilla/firefox/6j54aqdc.default-1448368191400/extensions/asciidoctor-firefox-addon@asciidoctor.org.xpi!/");
user_pref("extensions.asciidoctor-firefox-addon@asciidoctor.org.sdk.version", "0.4.0");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"langpack-fr@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/home/sarace/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-fr@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"asciidoctor-firefox-addon@asciidoctor.org\":{\"version\":\"0.4.0\",\"type\":\"extension\",\"descriptor\":\"/home/sarace/.mozilla/firefox/6j54aqdc.default-1448368191400/extensions/asciidoctor-firefox-addon@asciidoctor.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1450020597);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/asciidoc");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.xpiState", "{\"app-system-user\":{\"langpack-fr@firefox.mozilla.org\":{\"d\":\"/home/sarace/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-fr@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0\",\"st\":1436376576000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1437932489000,\"mt\":1436376282000}},\"app-profile\":{\"asciidoctor-firefox-addon@asciidoctor.org\":{\"d\":\"/home/sarace/.mozilla/firefox/6j54aqdc.default-1448368191400/extensions/asciidoctor-firefox-addon@asciidoctor.org.xpi\",\"e\":true,\"v\":\"0.4.0\",\"st\":1448569915000}}}");
user_pref("gecko.buildID", "20150708165822");
user_pref("gecko.mstone", "39.0");
user_pref("idle.lastDailyNotification", 1450021196);
user_pref("media.gmp-manager.buildID", "20150708165822");
user_pref("media.gmp-manager.lastCheck", 1450020178);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1450021197);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1450021197);
user_pref("toolkit.startup.last_success", 1450036240);
user_pref("toolkit.telemetry.previousBuildID", "20150708165822");
